services:

  biz:
    build:
      context: ./biz
      dockerfile: Dockerfile
    image: biz-image
    container_name: biz-container
    ports:
      - "8081:8081"
    networks:
      - report-noti

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    image: etl-image
    container_name: etl-container
    ports:
      - "8082:8082"
    networks:
      - report-noti

networks:
  report-noti:
    driver: bridge